# Generated by Django 5.2.17 on 2026-09-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatthread_visibility'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_thread__b4c881_idx',
            old_name='chat_chatme_thread__6547b5_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_thread__a0f205_idx',
            old_name='chat_chatme_thread__f7e35e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatthread',
            new_name='chat_chatth_patient_53a14f_idx',
            old_name='chat_chattr_patient_158c9d_idx',
        ),
        migrations.RenameIndex(
            model_name='chatthread',
            new_name='chat_chatth_staff_i_636760_idx',
            old_name='chat_chattr_staff_i_970aa0_idx',
        ),
    ]
