plugins {
    id 'com.android.application'
}

android {
    namespace 'uz.medconnect.app'
    compileSdk 35

    defaultConfig {
        applicationId 'uz.medconnect.app'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
        }
    }
}
