# Generated by Django 5.2.17 on 2026-09-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Qo‘shimcha ma’lumot'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.CharField(blank=True, max_length=500, verbose_name='Kasallik / murojaat sababi'),
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_type',
            field=models.CharField(blank=True, choices=[('TYPE1', 'Doctor Type 1')], max_length=20, null=True, verbose_name='Doktor turi'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Erkak'), ('FEMALE', 'Ayol')], max_length=10, verbose_name='Jins'),
        ),
    ]
